name: Weekly Security Scan

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering from any branch

permissions:
  contents: read

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Get latest release version
      id: get_version
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/mloda-ai/mloda/releases/latest | jq -r '.tag_name' | sed 's/^v//')
        echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
        echo "Latest mloda version: $LATEST_VERSION"

    - name: Run security scan with tox
      env:
        MLODA_VERSION: ${{ steps.get_version.outputs.version }}
      run: tox -e security
      timeout-minutes: 10
